services:
  techadvisor:
    image: akcitcamp:2025
    container_name: techadvisor
    build: .
    ports:
      - "7860:7860" # http://localhost:7860
    volumes:
      - "./agents/techadvisor:/home/akcit/techadvisor"
    command: ["python","/home/akcit/techadvisor/agente_gui.py"] 

  financeadvisor:
    image: akcitcamp:2025
    container_name: financeadvisor
    build: .
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8501:8501" # http://localhost:8501
    volumes:
      - "./agents/financeadvisor:/home/akcit/financeadvisor"
    working_dir: /home/akcit/financeadvisor
    command: ["/bin/bash", "-c", "/home/akcit/financeadvisor/run_app.sh"]

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  jupyter:
    image: akcitcamp:2025
    container_name: jupyter
    build: .
    ports:
      - "8888:8888" # http://localhost:8888
    volumes:
      - "./agents:/home/akcit/"
    working_dir: /home/akcit/
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=", "--NotebookApp.password="]
